# Generated by Django 5.1.2 on 2024-11-04 13:04

import my_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_user_activation_code_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', my_auth.models.UserManager()),
            ],
        ),
    ]
