# Generated by Django 5.1.2 on 2024-11-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
