# Generated by Django 5.1.2 on 2025-02-24 05:16

import volunteer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', volunteer.models.UserManager()),
            ],
        ),
    ]
