# Generated by Django 5.1.2 on 2025-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with this email address already exists.'}, help_text='Enter an email address in format: email@domain.com.', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
