# Generated by Django 5.1.2 on 2025-02-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_user_activation_code_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
