# Generated by Django 5.1.2 on 2025-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', error_messages={'unique': 'A user with this email address already exists.'}, help_text='Enter an email address in format: email@domain.com.', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
